# Generated by Django 5.0.6 on 2024-07-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('role', models.CharField(choices=[('user', 'User'), ('example', 'Example')], default='user', max_length=16)),
                ('photo', models.ImageField(upload_to='person/')),
                ('headline', models.TextField(blank=True, max_length=256)),
                ('bio_short', models.TextField(max_length=1204)),
                ('bio', models.TextField(max_length=1204)),
                ('copyright_date', models.DateField()),
                ('updated_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=128)),
                ('occupation', models.CharField(choices=[('researcher', 'Researcher'), ('developer', 'Developer'), ('student', 'Student'), ('other', 'Please specify')], default='researcher', max_length=32)),
                ('occupation_other', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(choices=[('collaboration', 'Seek collaboration'), ('interest', 'Interested in my work'), ('consultancy', 'Consultation in AI application or research'), ('other', 'Please specify')], default='collaboration', max_length=32)),
                ('type_other', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
                ('subscribed_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField(max_length=512)),
                ('url', models.URLField(max_length=128)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('other', 'Other')], max_length=16)),
                ('institution', models.CharField(max_length=64)),
                ('address', models.EmailField(max_length=128)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('office', 'Office Phone'), ('mobile', 'Mobile')], default='office', max_length=8)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('institution', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('fulltime', 'Fulltime'), ('part-time', 'Part time'), ('voluntary', 'Voluntary'), ('self-employed', 'Self-employed'), ('other', 'Other')], default='primary', max_length=64)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=16)),
                ('province', models.CharField(max_length=32)),
                ('postcode', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=32)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='pages.position')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('image', models.ImageField(upload_to='projects/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('role', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('lts', 'Long-term support'), ('deprecated', 'Deprecated')], default='active', max_length=16)),
                ('url', models.URLField()),
                ('featured', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=512)),
                ('authors', models.TextField(max_length=512)),
                ('summary', models.TextField(max_length=512)),
                ('abstract', models.TextField(max_length=1024)),
                ('doi', models.URLField(max_length=128)),
                ('url', models.URLField(max_length=128)),
                ('image', models.ImageField(upload_to='publications')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('preprint', 'Preprint'), ('journal', 'Journal'), ('conference', 'Conference'), ('report', 'Report'), ('other', 'Other')], default='preprint', max_length=16)),
                ('publisher', models.CharField(max_length=64)),
                ('featured', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('image', models.ImageField(upload_to='talks/')),
                ('summary', models.TextField(max_length=512)),
                ('description', models.TextField(max_length=1024)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('keynote', 'Keynote'), ('conference', 'Conference'), ('poster', 'Poster'), ('public', 'Public')], default='conference', max_length=16)),
                ('status', models.CharField(choices=[('keynote', 'Keynote'), ('conference', 'Conference'), ('poster', 'Poster'), ('public', 'Public')], default='completed', max_length=16)),
                ('url', models.URLField()),
                ('featured', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='pages.person')),
            ],
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField(max_length=256)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weblinks', to='pages.person')),
            ],
        ),
    ]
