# Generated by Django 5.0.6 on 2024-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
